Update git submodules
* Update Vector from branch 'master'
  to daf6a798c428845d1fba7635cb7a033b8c0870a1
  - TypeError: data.collapseCondition is not a function
    
    Lots of logspam relating to this error. If data is {}
    this error will be thrown which is possible given the
    code.
    
    This is possible if a gadget rewrites tabs
    
    e.g.
    $( '#p-views ul' ).remove().append($('<ul>'))
    
    Change-Id: I0d3f391fccdb38758fb3cfd7e84889143d479b1e