Update git submodules
* Update webplatform from branch 'master'
  - Merge "When you use the short open tag, you're coding with Satan!"
  - When you use the short open tag, you're coding with Satan!
    
    It's also not very cross-platform compatible and can cause "fun" issues,
    like this one:
    
    Fatal error: Call to undefined method
    WebPlatformTemplate::renderEditButton() in ../skins/WebPlatform/WebPlatformTemplate.class.php on line 117
    
    Change-Id: I85d73f986ba780335091fd86fa2857dad1b5e4d1