Update git submodules
* Update Metrolook from branch 'master'
  to 956c43444e2ae65b4e1a0611a732d306cbbf86d3
  - Fix JS error: Uncaught TypeError: $(...).lastTabIndex is not a function
    
    Per T234581, the 'jquery.tabIndex' ResourceLoader module was deprecated in MW 1.34 and removed from core in 1.35.
    As per https://www.mediawiki.org/wiki/ResourceLoader/Migration_guide_(users)#jquery.tabIndex I've chosen to remove the problematic line of code here.
    
    Change-Id: If7ed630fea19105a6d8f3f79581e3e12a886c8e2